# Generated by Django 3.2.16 on 2022-12-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='check_interval',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='normal_interval',
            field=models.IntegerField(default=3600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='port',
            field=models.IntegerField(default=81),
            preserve_default=False,
        ),
    ]
