# Generated by Django 4.0.4 on 2022-12-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='modifier',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
