# Generated by Django 4.0.4 on 2022-10-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='image',
        ),
    ]
