# Generated by Django 3.2.16 on 2022-12-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20221224_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='ipadress',
            field=models.GenericIPAddressField(default=19216821885),
            preserve_default=False,
        ),
    ]
