# Generated by Django 4.0.4 on 2022-10-24 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_building_or_plant_system_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='date',
            new_name='arduino_date',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='server_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
