# Generated by Django 4.0.4 on 2022-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_date_dataentry_arduino_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='interval',
            field=models.IntegerField(default=3600),
            preserve_default=False,
        ),
    ]
